### ISSUE TITLE
Area Model Multiplication Main checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/area-model-multiplication#1]
## Design
- [x] **Sim folder and design doc created** (Date: 01/19/2016) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Sim suggestions doc reviewed**
- [x] **Learning goals and standards identified** (Date: 03/21/2016)
- [x] **Design concept complete**  (Date: 05/05/2016)
- [x] **Wireframes complete** (Date: 08/31/2016) 
- [x] **Mockups complete** (Date: 06/08/2017) 
  - [x] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion** 
- [x] **Interviews complete** (Date: //) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //) 
  - [ ] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [ ] **Pre-publication items** 
  - [x] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Add an activity
  - [x] Sim primer draft
  - [x] Verify credits
- [ ] **Post-publication items** 
  - [ ] Add the simulation to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [ ] Add to Edmodo
  - [ ] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [ ] Hold postmortem if applicable (Date: //) 

## Implementation
- [x] **Repository created** (Date: 08/31/2016)
  - [x] simula-rasa used to create project skeleton
  - [x] README.md created using `grunt unpublished-readme`
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to chipper/data/ files
- [x] **Development started** (Date: 05/09/2017)
- [x] **Sim is "feature complete"** (Date: 1/12/2018) 
- [ ] **Code review completed** (Date: //) 
- [x] **Published** (Date: 4/24/2018) 
  - [x] README.md updated using `grunt published-readme` (in master and release branch)
 
## QA
- [ ] **Dev testing started** (Date: //) 
- [ ] **Dev testing completed** (Date: //) 
- [ ] **First RC published** (Date: //)
  - [ ] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [ ] **RC testing completed** (Date: //)

**Comment by ariel-phet** [comment]
## Design
- [ ] **Sim folder and design doc created** (Date: //) 
  - [ ] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [ ] Place design doc in the sim folder
- [ ] **Sim suggestions doc reviewed**
- [ ] **Learning goals and standards identified** (Date: //)
- [ ] **Design concept complete**  (Date: //)
- [ ] **Wireframes complete** (Date: //) 
- [ ] **Mockups complete** (Date: //) 
  - [ ] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion** 
- [ ] **Interviews complete** (Date: //) 
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //) 
  - [ ] Performance acceptable
  - [ ] Carefully review ?showPointerAreas
  - [ ] No new feature requests
- [ ] **Pre-publication items** 
  - [ ] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [ ] Auxilary screenshots (up to 3 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Add an activity
  - [ ] Sim primer draft
  - [ ] Verify credits
- [ ] **Post-publication items** 
  - [ ] Add to Edmodo
  - [ ] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [ ] Hold postmortem if applicable (Date: //) 

## Implementation
- [ ] **Repository created** (Date: //)
  - [ ] simula-rasa used to create project skeleton
  - [ ] README.md created using `grunt unpublished-readme`
  - [ ] Collaborators added (such as QA team, designers, etc)
  - [ ] standard GitHub label set applied
  - [ ] repository added to chipper/data/ files
- [ ] **Development started** (Date: //)
- [ ] **Sim is "feature complete"** (Date: //) 
- [ ] **Code review completed** (Date: //) 
- [ ] **Published** (Date: //) 
  - [ ] README.md updated using `grunt published-readme` (in master and release branch)
 
## QA
- [ ] **Dev testing started** (Date: //) 
- [ ] **Dev testing completed** (Date: //) 
- [ ] **First RC published** (Date: //)
  - [ ] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [ ] **RC testing completed** (Date: //)
